# SwiftLint Configuration

# Paths to include during linting
included:
  - imq-core/Sources
  - imq-gui/Sources

# Paths to ignore during linting
excluded:
  - imq-core/.build
  - imq-gui/.build
  - imq-core/Tests
  - imq-gui/Tests
  - .build

# Disable rules
disabled_rules:
  - trailing_whitespace
  - todo

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - sorted_first_last
  - contains_over_first_not_nil
  - force_unwrapping

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1200

function_body_length:
  warning: 80
  error: 120

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - db
    - pr
    - ci
    - at

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 5

# Reporter type
reporter: "xcode"
